steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - beta
  - functions
  - deploy
  - hello_http
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python39
  - 
  - >
    --set-secrets 
    'Telegram_API_Key=Telgram_API_Key:latest, 
    Telegram_API_Hash=Telegram_API_Hash:latest, 
    Telegram_API_ID=Telegram_API_ID:latest'