steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - gcloud
  - functions
  - deploy
  - hello_http
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python39
  secretEnv: ['Telegram_API_Key', 'Telegram_API_Hash', 'Telegram_API_ID']
availableSecrets:
  secretManager:
  - versionName: projects/911288896089/secrets/Telegram_API_Key
    env: 'Telegram_API_Key'
  - versionName: projects/911288896089/secrets/Telegram_API_Hash
    env: 'Telegram_API_Hash'
  - versionName: projects/911288896089/secrets/Telegram_API_ID
    env: 'Telegram_API_ID'