steps:
- name: 'docker.io/library/python:3.9'
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install -r requirements-test.txt && pytest'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - beta
  - functions
  - deploy
  - hello_http
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python39