steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello_http
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python39
availableSecrets:
  secretManager:
  - versionName: projects/911288896089/secrets/Telegram_API_Key/versions/1
    env: 'Telegram_API_Key'
  - versionName: projects/911288896089/secrets/Telegram_API_Hash/versions/1
    env: 'Telegram_API_Hash'
  - versionName: projects/911288896089/secrets/Telegram_API_ID/versions/1
    env: 'Telegram_API_ID'